- title: Automations
  icon: "mdi:auto-fix"
  path: automations
  badges: []
  cards:
    - type: "custom:auto-entities"
      card:
        type: entities
        title: Automations
      filter:
        include:
          - domain: automation
    - type: "custom:auto-entities"
      card:
        type: entities
        title: Scripts
      filter:
        include:
          - domain: script
