# WoL Twan-PC
- platform: wake_on_lan
  name: office_twan_pc
  mac: "BC:AE:C5:59:34:6F"
  host: 10.0.7.1
  broadcast_address: 10.0.7.253
  turn_off:
    service: shell_command.sleep_windows_pc
    data:
      userhost: antoi@10.0.7.1

# WoL Caro-PC
- platform: wake_on_lan
  name: office_caro_pc
  mac: "50:E5:49:32:6A:2B"
  host: 10.0.7.2
  broadcast_address: 10.0.7.253
  turn_off:
    service: shell_command.sleep_windows_pc
    data:
      userhost: lengl@10.0.7.2