- platform: template
  sensors:
    # Living temperature
    living_climate_temperature:
      unique_id: living_climate_temperature
      unit_of_measurement: °C
      value_template: "{{ state_attr('climate.living_thermostat', 'current_temperature') }}"
      device_class: temperature

    # Datacenter temperature
    dc_climate_temperature:
      unique_id: dc_climate_temperature
      unit_of_measurement: °C
      value_template: "{{ states('sensor.snmp_pdu01_temperature') }}"
      device_class: temperature

    # Datacenter humidity
    dc_climate_humidity:
      unique_id: dc_climate_humidity
      unit_of_measurement: "%"
      value_template: "{{ states('sensor.snmp_pdu01_humidity') }}"
      device_class: humidity

- platform: snmp
  name: snmp_pdu01_temperature
  host: pdu01.i
  baseoid: 1.3.6.1.4.1.1718.3.2.5.1.6.1.1
  accept_errors: true
  value_template: "{{ ((value | int) / 10) | float }}"
  unit_of_measurement: °C

- platform: snmp
  name: snmp_pdu01_humidity
  host: pdu01.i
  baseoid: 1.3.6.1.4.1.1718.3.2.5.1.10.1.1
  accept_errors: true
  unit_of_measurement: "%"
