- platform: moon
- platform: season
- platform: template
  sensors:
    sun_elevation:
      unique_id: sun_elevation
      unit_of_measurement: °
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"

- platform: seventeentrack
  username: !secret 17track_email
  password: !secret 17track_password
