- platform: template
  sensors:
    pihole_ads_blocked_today:
      friendly_name: Ads Blocked Today
      icon_template: mdi:close-octagon-outline
      unit_of_measurement: ads
      value_template: "{{ states('sensor.pihole_01_ads_blocked_today')|int + states('sensor.pihole_02_ads_blocked_today')|int }}"
    pihole_ads_percentage_blocked_today:
      friendly_name: Ads Percentage Blocked Today
      icon_template: mdi:close-octagon-outline
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.pihole_ads_blocked_today')|int / states('sensor.pihole_dns_queries_today')|int) * 100)|round(2) }}"
    pihole_dns_queries_cached:
      friendly_name: DNS Queries Cached
      icon_template: mdi:comment-question-outline
      unit_of_measurement: queries
      value_template: "{{ states('sensor.pihole_01_dns_queries_cached')|int + states('sensor.pihole_02_dns_queries_cached')|int }}"
    pihole_dns_queries_today:
      friendly_name: DNS Queries Today
      icon_template: mdi:comment-question-outline
      unit_of_measurement: queries
      value_template: "{{ states('sensor.pihole_01_dns_queries_today')|int + states('sensor.pihole_02_dns_queries_today')|int }}"
    pihole_dns_queries_percentage_cached:
      friendly_name: DNS Queries Percentage Cached
      icon_template: mdi:comment-question-outline
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.pihole_dns_queries_cached')|int / states('sensor.pihole_dns_queries_today')|int) * 100)|round(2) }}"