# Alarmm clock based on phone next alarm
- alias: alarmclock
  trigger:
    - platform: template
      value_template: >-
        {% set dummy = states("sensor.time") %}
        {{ (utcnow() | as_timestamp) == ((states('sensor.app_twanphone_next_alarm') | as_timestamp) - 60*15) }}
  condition:
    - condition: state
      entity_id: person.antoine
      state: 'home'
  action:
    - service: script.alarmclock